from .teste import Teste
from .user import Usuario
from .category import Categoria
from .specialty import Especialidade
from .instructor import Instrutor
from .course import Curso
from .module import Modulo
from .lesson import Aula
from .enrollment import Matricula
from .assessment import DesempenhoAluno
from .evaluation import AvaliacaoCurso
from .progress import ProgressoAulas
from .certificate import Certificado
from .level import Nivel
