"""update teste com idade

Revision ID: 313f30c6722b
Revises: 587943d93bb9
Create Date: 2025-11-19 23:42:53.630613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '313f30c6722b'
down_revision: Union[str, None] = '587943d93bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teste_migration', sa.Column('idade', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teste_migration', 'idade')
    # ### end Alembic commands ###
