"""criar tabelas matriculas, avaliacoes, progresso_aulas e certificados

Revision ID: 4fbd95d1af1b
Revises: 72cdb7d6d099
Create Date: 2025-12-03 01:38:40.913289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fbd95d1af1b'
down_revision: Union[str, None] = '72cdb7d6d099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matriculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('data_matricula', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status_matricula', sa.String(length=12), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matriculas_id'), 'matriculas', ['id'], unique=False)
    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=500), nullable=True),
    sa.Column('data_avaliacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matricula_id'], ['matriculas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacoes_id'), 'avaliacoes', ['id'], unique=False)
    op.create_table('certificados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matricula_id', sa.Integer(), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_emissao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matricula_id'], ['matriculas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula_id')
    )
    op.create_index(op.f('ix_certificados_id'), 'certificados', ['id'], unique=False)
    op.create_table('progresso_aulas',
    sa.Column('matricula_id', sa.Integer(), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=False),
    sa.Column('concluido', sa.Boolean(), nullable=False),
    sa.Column('progresso_percentual', sa.Integer(), nullable=False),
    sa.Column('data_ultimo_acesso', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], ),
    sa.ForeignKeyConstraint(['matricula_id'], ['matriculas.id'], ),
    sa.PrimaryKeyConstraint('matricula_id', 'aula_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progresso_aulas')
    op.drop_index(op.f('ix_certificados_id'), table_name='certificados')
    op.drop_table('certificados')
    op.drop_index(op.f('ix_avaliacoes_id'), table_name='avaliacoes')
    op.drop_table('avaliacoes')
    op.drop_index(op.f('ix_matriculas_id'), table_name='matriculas')
    op.drop_table('matriculas')
    # ### end Alembic commands ###
