"""update teste table

Revision ID: 587943d93bb9
Revises: 7c51cc8a7522
Create Date: 2025-11-19 23:31:40.959108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '587943d93bb9'
down_revision: Union[str, None] = '7c51cc8a7522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teste_migration', sa.Column('descricao', sa.String(length=255), nullable=True))
    op.add_column('teste_migration', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('teste_migration', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teste_migration', 'updated_at')
    op.drop_column('teste_migration', 'created_at')
    op.drop_column('teste_migration', 'descricao')
    # ### end Alembic commands ###
