"""add relationships constraints for users-instructors-enrollments

Revision ID: 5bca34dcc998
Revises: aaa0c2bf325a
Create Date: 2025-12-03 23:48:06.546033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bca34dcc998'
down_revision: Union[str, None] = 'aaa0c2bf325a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'instrutores', 'usuarios', ['id'], ['id'])
    op.create_foreign_key(None, 'matriculas', 'usuarios', ['aluno_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matriculas', type_='foreignkey')
    op.drop_constraint(None, 'instrutores', type_='foreignkey')
    # ### end Alembic commands ###
