"""sincronizar alterações manuais do schema

Revision ID: 7266d8577765
Revises: f1e840b16409
Create Date: 2025-12-11 12:25:30.010938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7266d8577765'
down_revision: Union[str, None] = 'f1e840b16409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_avaliacoes_id', table_name='avaliacoes')
    op.drop_table('avaliacoes')
    op.create_foreign_key(None, 'matriculas', 'cursos', ['curso_id'], ['id'])
    op.create_foreign_key(None, 'modulos', 'cursos', ['curso_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modulos', type_='foreignkey')
    op.drop_constraint(None, 'matriculas', type_='foreignkey')
    op.create_table('avaliacoes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('matricula_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nota', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comentario', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('data_avaliacao', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['matricula_id'], ['matriculas.id'], name='avaliacoes_matricula_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='avaliacoes_pkey')
    )
    op.create_index('ix_avaliacoes_id', 'avaliacoes', ['id'], unique=False)
    # ### end Alembic commands ###
