"""adicionar coluna nivel na tabela cursos

Revision ID: 72cdb7d6d099
Revises: 79577d4760cd
Create Date: 2025-12-03 00:19:45.246441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72cdb7d6d099'
down_revision: Union[str, None] = '79577d4760cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('nivel', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cursos', 'nivel')
    # ### end Alembic commands ###
