"""atualizar tabela progresso_aulas: adicionar data_conclusao e remover data_ultimo_acesso

Revision ID: 8ff361ce4232
Revises: 4fbd95d1af1b
Create Date: 2025-12-03 02:12:27.067016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ff361ce4232'
down_revision: Union[str, None] = '4fbd95d1af1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progresso_aulas', sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('progresso_aulas', 'data_ultimo_acesso')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progresso_aulas', sa.Column('data_ultimo_acesso', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('progresso_aulas', 'data_conclusao')
    # ### end Alembic commands ###
