"""update teste sem descricao

Revision ID: a8b79aa0e0d8
Revises: 313f30c6722b
Create Date: 2025-11-19 23:48:48.691991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b79aa0e0d8'
down_revision: Union[str, None] = '313f30c6722b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teste_migration', 'descricao')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teste_migration', sa.Column('descricao', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
