"""atualizar tabela usuarios: adicionar sobrenome e ultima_atualizacao

Revision ID: aaa0c2bf325a
Revises: ad238654c114
Create Date: 2025-12-03 02:34:11.217357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa0c2bf325a'
down_revision: Union[str, None] = 'ad238654c114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('sobrenome', sa.String(length=45), nullable=True))
    op.add_column('usuarios', sa.Column('ultima_atualizacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'ultima_atualizacao')
    op.drop_column('usuarios', 'sobrenome')
    # ### end Alembic commands ###
