"""atualizar tabela progresso_aulas: adicionar data_conclusao e remover data_ultimo_acesso

Revision ID: ad238654c114
Revises: 8ff361ce4232
Create Date: 2025-12-03 02:14:53.269659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad238654c114'
down_revision: Union[str, None] = '8ff361ce4232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
