"""criar tabelas especialidade e instrutores

Revision ID: be598eb781bd
Revises: 1396308a0d90
Create Date: 2025-12-02 02:58:16.079658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be598eb781bd'
down_revision: Union[str, None] = '1396308a0d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_especialidade_id'), 'especialidade', ['id'], unique=False)
    op.create_table('instrutores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('especialidade', sa.Integer(), nullable=False),
    sa.Column('biografia', sa.String(length=300), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultima_alteracao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['especialidade'], ['especialidade.id'], ),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrutores_id'), 'instrutores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instrutores_id'), table_name='instrutores')
    op.drop_table('instrutores')
    op.drop_index(op.f('ix_especialidade_id'), table_name='especialidade')
    op.drop_table('especialidade')
    # ### end Alembic commands ###
