"""cria tabelas de avaliacao e desempenho

Revision ID: f1e840b16409
Revises: 8d91e1765f92
Create Date: 2025-12-10 14:18:47.872657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e840b16409'
down_revision: Union[str, None] = '8d91e1765f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
