#!/bin/sh
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
MODEL="$ROOT/backend/backend/app/models/uploaded_file.py"
SERVICE="$ROOT/backend/backend/app/services/file_storage.py"
ROUTER="$ROOT/backend/backend/app/routers/files.py"
MIGRATION="$ROOT/backend/backend/alembic/versions_v2/0004_file_upload.py"
TESTS="$ROOT/backend/backend/tests/test_file_upload.py"
UI="$ROOT/frontend/src/pages/Files/index.tsx"
API_CONFIG="$ROOT/frontend/src/services/api/apiConfig.ts"
ROUTES="$ROOT/frontend/src/routes/AppRoutes.tsx"
COMPOSE="$ROOT/docker-compose.yml"
NGINX="$ROOT/infra/nginx/nginx.conf"
DOCS="$ROOT/docs/evaluation/FILE_UPLOAD.md"

for file in "$MODEL" "$SERVICE" "$ROUTER" "$MIGRATION" "$TESTS" "$UI" "$API_CONFIG" "$ROUTES" "$COMPOSE" "$NGINX" "$DOCS"; do
  test -f "$file"
done

grep -q 'down_revision = "0003_rbac_user_state"' "$MIGRATION"
grep -q 'owner_id' "$MODEL"
grep -q 'storage_name' "$MODEL"
grep -q 'uuid.uuid4' "$SERVICE"
grep -q 'sha256' "$SERVICE"
grep -q 'image/png' "$SERVICE"
grep -q 'image/jpeg' "$SERVICE"
grep -q 'image/webp' "$SERVICE"
grep -q 'application/pdf' "$SERVICE"
grep -q 'text/plain' "$SERVICE"
grep -q '_validate_signature' "$SERVICE"
grep -q '_policy_for_extension' "$SERVICE"
grep -q 'GENERIC_DECLARED_TYPES' "$SERVICE"
grep -q 'application/octet-stream' "$SERVICE"
grep -q 'HTTP_413_REQUEST_ENTITY_TOO_LARGE' "$SERVICE"
grep -q '@router.post' "$ROUTER"
grep -q '@router.get("/{file_id}/content")' "$ROUTER"
grep -q '@router.delete' "$ROUTER"
grep -q 'user\["role"\] != "admin"' "$ROUTER"
grep -q 'onUploadProgress' "$UI"
grep -q '<progress' "$UI"
grep -q 'Visualizar' "$UI"
grep -q 'Baixar' "$UI"
grep -q 'Excluir' "$UI"
grep -q 'fileExtension' "$UI"
grep -q 'policyForFile' "$UI"
grep -q 'canonicalContentType' "$UI"
grep -q 'GENERIC_BROWSER_TYPES' "$UI"
grep -q 'application/octet-stream' "$UI"
grep -q 'path="arquivos"' "$ROUTES"
grep -q 'file_storage:/app/storage/uploads' "$COMPOSE"
grep -q 'client_max_body_size 13m' "$NGINX"

# Browser multipart requests must keep the boundary generated by Axios/the browser.
# A manually forced multipart Content-Type can omit that boundary and make FastAPI
# reject uploads even while curl-based smoke tests still pass.
! grep -q 'Content-Type.*multipart/form-data' "$UI"
! grep -q 'Content-Type.*application/json' "$API_CONFIG"

# A real browser may report a supported file as an empty MIME or generic
# application/octet-stream. The client must not index policy exclusively by
# file.type, and the server must still validate the actual signature.
! grep -q 'FILE_POLICIES\[file\.type\]' "$UI"
grep -q 'application/octet-stream' "$TESTS"
grep -q 'generic_wrong_signature' "$TESTS"

# Unsafe active document types must not be part of the allowlist.
! grep -q 'text/html.*FilePolicy' "$SERVICE"
! grep -q 'image/svg+xml.*FilePolicy' "$SERVICE"

echo "File Upload structural/security check passed."
